print("Bonjour! aujourd'hui je présenterai ma famille et quelques objets que j'aime chez moi")
print("les membres de ma famille")
print("****1.ma mère****")
print("c'est ma mère. son nom est Sarika Gupta")
print("elle a 42 ans")
print("c'est une scientifique")
print("son hobby est de faire les choses qui appliquent le plus le cerveau")
print("**** 2.mon père****")
print("c'est mon père, il s'appelle Neeraj Sehgal")
print("il a 42 ans")
print("son hobby est de coder")
print("****3.mon frère****")
print("c'est mon frère, il s'appelle Aadvik Sehgal")
print("il a 6 ans")
print("son hobby est de jouer à des jeux")
print("****4.moi même****")
print("c'est moi! je m'appelle Akshaj Sehgal")
print("j'ai 10 ans") 
print("mon hobby est d'apprendre sur différents pays")
print(" **** 5. mes cousins **** ")
print("ce sont mes cousins [y compris moi-même]")
print("celui en haut à gauche est ma **** cousine sœur shambhavi ****")
print("elle a 5 ansson passe-temps est de méditer et de lire des mantras")
print("celui en bas à droite est ma **** cousine-sœur. Son nom est Aarna ****")
print("elle a 6 ans")
print("son hobby est de danser")
print("celui en bas à gauche est mon **** frère Aadvik **** et celui en haut à droite est **** moi-même! [Akshaj] ****")
print("les objets que j'aime chez moi")
print("****1. mes jouets****")
print("Bien sûr, j'aimerai mes jouets parce que je joue avec eux et jouer avec des jouets est amusant!")
print("2. **** Jeux **** ")
print("j'aime les jeux parce que c'est amusant de jouer et cela vous engage et vous attire pour y jouer")
print("3. **** le réfrigérateur **** ")
print("j'aime le réfrigérateur car il préserve vos articles et sans le réfrigérateur, vous ne pouvez pas conserver les articles et vous ne pouvez pas garder les aliments frais")



